#set UnusedPin
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]

#system slock
set_property PACKAGE_PIN W19 [get_ports clk50m]
set_property IOSTANDARD LVCMOS33 [get_ports clk50m]
create_clock -period 20.000 -name sys_clk_50m -waveform {0.000 10.000} [get_ports clk50m]
set_clock_groups -asynchronous -group [get_clocks sys_clk_50m -include_generated_clocks]

#reset active low,
set_property PACKAGE_PIN D21 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]

#led
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN W21 [get_ports {led[2]}]
set_property PACKAGE_PIN V22 [get_ports {led[1]}]
set_property PACKAGE_PIN U22 [get_ports {led[0]}]


#…„œÒÕ∑£®∞Â‘ÿΩ”ø⁄)
set_property PACKAGE_PIN N20 [get_ports {camera_data[7]}]
set_property PACKAGE_PIN K19 [get_ports {camera_data[6]}]
set_property PACKAGE_PIN K16 [get_ports {camera_data[5]}]
set_property PACKAGE_PIN L16 [get_ports {camera_data[4]}]
set_property PACKAGE_PIN L18 [get_ports {camera_data[3]}]
set_property PACKAGE_PIN M18 [get_ports {camera_data[2]}]
set_property PACKAGE_PIN M16 [get_ports {camera_data[1]}]
set_property PACKAGE_PIN M15 [get_ports {camera_data[0]}]
set_property PACKAGE_PIN N19 [get_ports camera_href]
set_property PACKAGE_PIN M17 [get_ports camera_sclk]
set_property PACKAGE_PIN N18 [get_ports camera_sdat]
set_property PACKAGE_PIN J16 [get_ports camera_vsync]
set_property PACKAGE_PIN K18 [get_ports camera_xclk]
set_property PACKAGE_PIN M20 [get_ports camera_pclk]


set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports camera_xclk]
set_property IOSTANDARD LVCMOS33 [get_ports camera_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports camera_href]
set_property IOSTANDARD LVCMOS33 [get_ports camera_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports camera_sdat]
set_property PULLUP true [get_ports camera_sdat]
set_property IOSTANDARD LVCMOS33 [get_ports camera_sclk]
set_property PULLUP true [get_ports camera_sclk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets camera_pclk_IBUF]

#HDMI
set_property PACKAGE_PIN J19 [get_ports hdmi_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN K21 [get_ports {hdmi_dat_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_dat_p[0]}]
set_property PACKAGE_PIN J20 [get_ports {hdmi_dat_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_dat_p[1]}]
set_property PACKAGE_PIN J22 [get_ports {hdmi_dat_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_dat_p[2]}]
set_property PACKAGE_PIN M22 [get_ports hdmi_oe]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_oe]

#VGA
set_property IOSTANDARD LVCMOS33 [get_ports o_disp_de]
set_property IOSTANDARD LVCMOS33 [get_ports disp_clk]
set_property PACKAGE_PIN B17 [get_ports o_disp_de]
set_property PACKAGE_PIN A19 [get_ports disp_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {disp_rgb[*]}]
set_property PACKAGE_PIN E16 [get_ports {disp_rgb[23]}]
set_property PACKAGE_PIN D16 [get_ports {disp_rgb[22]}]
set_property PACKAGE_PIN F18 [get_ports {disp_rgb[21]}]
set_property PACKAGE_PIN E18 [get_ports {disp_rgb[20]}]
set_property PACKAGE_PIN F19 [get_ports {disp_rgb[19]}]
set_property PACKAGE_PIN F20 [get_ports {disp_rgb[18]}]
set_property PACKAGE_PIN E19 [get_ports {disp_rgb[17]}]
set_property PACKAGE_PIN D19 [get_ports {disp_rgb[16]}]
set_property PACKAGE_PIN A20 [get_ports {disp_rgb[15]}]
set_property PACKAGE_PIN B20 [get_ports {disp_rgb[14]}]
set_property PACKAGE_PIN F14 [get_ports {disp_rgb[13]}]
set_property PACKAGE_PIN F13 [get_ports {disp_rgb[12]}]
set_property PACKAGE_PIN D15 [get_ports {disp_rgb[11]}]
set_property PACKAGE_PIN D14 [get_ports {disp_rgb[10]}]
set_property PACKAGE_PIN E17 [get_ports {disp_rgb[9]}]
set_property PACKAGE_PIN F16 [get_ports {disp_rgb[8]}]
set_property PACKAGE_PIN A16 [get_ports {disp_rgb[7]}]
set_property PACKAGE_PIN A13 [get_ports {disp_rgb[6]}]
set_property PACKAGE_PIN A18 [get_ports {disp_rgb[5]}]
set_property PACKAGE_PIN B16 [get_ports {disp_rgb[4]}]
set_property PACKAGE_PIN B15 [get_ports {disp_rgb[3]}]
set_property PACKAGE_PIN C17 [get_ports {disp_rgb[2]}]
set_property PACKAGE_PIN D17 [get_ports {disp_rgb[1]}]
set_property PACKAGE_PIN B18 [get_ports {disp_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_disp_hs]
set_property IOSTANDARD LVCMOS33 [get_ports o_disp_vs]
set_property PACKAGE_PIN C18 [get_ports o_disp_hs]
set_property PACKAGE_PIN C19 [get_ports o_disp_vs]

#bit compress spix4 speed up
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]